export const buildings = [
  "Academic Health Center 2",
  "Academic Health Center 3",
  "Academic Health Center 4",
  "Academic Health Center 5",
  "Charles E. Perry",
  "Comp, Arts, Sci & Educat",
  "College of Business Complex",
  "Chem & Physics",
  "Deuxieme Maison",
  "Everglades Residence Hall",
  "Engineering Center",
  "Patricia&PhilipFrostMuseum",
  "Graham Center",
  "Green Library",
  "Labor Center",
  "Mgmt and New Growth Opp",
  "Mgmt & Advanced Resrch Ctr",
  "Ocean Bank Convoc Center",
  "Owa Ehan",
  "Paul Cejas Architecture",
  "PG5 Market Station",
  "Parking Garage 6",
  "Ryder Business",
  "Sch. Inter.&Public Affairs",
  "Stocker Astroscience Center",
  "Studio",
  "Viertes Haus",
  "West 1",
  "West 9",
  "West 10",
  "Wertheim Prf Arts Ctr",
].sort();